

server:
   port: 8042
   
   
   

spring:
   datasource:
      url: jdbc:mysql://localhost:3306/demodb?useSSL=false
      username: root
      password: StrangeVin@1000
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate: 
         ddl-auto: update
      show-sql: true


   
   